import type { Command } from "commander";
import * as clack from "@clack/prompts";
import chalk from "chalk";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

// ---------------------------------------------------------------------------
// Shell script generators
// ---------------------------------------------------------------------------

function zshScript(): string {
  return `\
#compdef sshm

_sshm() {
  local context state state_descr line
  typeset -A opt_args

  _arguments -C \\
    '(-h --help)'{-h,--help}'[show help]' \\
    '(-V --version)'{-V,--version}'[show version]' \\
    '1: :->command' \\
    '*: :->args'

  case $state in
    command)
      local commands
      commands=(
        'init:Initialise sshm — creates ~/.ssh/sshm/ and wires ~/.ssh/config'
        'sync:Force regenerate ~/.ssh/sshm/config from sshm.json'
        'host:Manage SSH hosts'
        'group:Manage host groups'
        'connect:Connect to a host'
        'c:Connect to a host (alias for connect)'
        'completion:Generate shell completion script'
      )
      _describe 'commands' commands
      ;;
    args)
      case $line[1] in
        connect|c)
          local hosts
          hosts=(\${(f)"\$(sshm --completions connect 2>/dev/null)"})
          _describe 'hosts' hosts
          ;;
        host)
          _sshm_host
          ;;
        group)
          _sshm_group
          ;;
      esac
      ;;
  esac
}

_sshm_host() {
  local state line
  _arguments -C \\
    '1: :->subcommand' \\
    '*: :->args'

  case $state in
    subcommand)
      local subcommands
      subcommands=(
        'add:Add a host'
        'edit:Edit a host'
        'remove:Remove a host'
        'list:List all hosts'
        'move:Move a host to a different group'
      )
      _describe 'host subcommands' subcommands
      ;;
    args)
      case $line[1] in
        edit|remove|move)
          local hosts
          hosts=(\${(f)"\$(sshm --completions host 2>/dev/null)"})
          _describe 'hosts' hosts
          ;;
      esac
      ;;
  esac
}

_sshm_group() {
  local state line
  _arguments -C \\
    '1: :->subcommand' \\
    '*: :->args'

  case $state in
    subcommand)
      local subcommands
      subcommands=(
        'add:Create a group'
        'edit:Edit a group'
        'remove:Remove a group'
        'list:List all groups'
      )
      _describe 'group subcommands' subcommands
      ;;
    args)
      case $line[1] in
        edit|remove)
          local groups
          groups=(\${(f)"\$(sshm --completions group 2>/dev/null)"})
          _describe 'groups' groups
          ;;
      esac
      ;;
  esac
}

_sshm
`;
}

function bashScript(): string {
  return `\
_sshm_completions() {
  local cur prev words cword
  _init_completion 2>/dev/null || {
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    words=("\${COMP_WORDS[@]}")
    cword=\$COMP_CWORD
  }

  local top_commands="init sync host group connect c completion"

  case "\${words[1]}" in
    connect|c)
      COMPREPLY=($(compgen -W "$(sshm --completions connect 2>/dev/null)" -- "$cur"))
      ;;
    host)
      case "\${words[2]}" in
        edit|remove|move)
          COMPREPLY=($(compgen -W "$(sshm --completions host 2>/dev/null)" -- "$cur"))
          ;;
        *)
          COMPREPLY=($(compgen -W "add edit remove list move" -- "$cur"))
          ;;
      esac
      ;;
    group)
      case "\${words[2]}" in
        edit|remove)
          COMPREPLY=($(compgen -W "$(sshm --completions group 2>/dev/null)" -- "$cur"))
          ;;
        *)
          COMPREPLY=($(compgen -W "add edit remove list" -- "$cur"))
          ;;
      esac
      ;;
    *)
      COMPREPLY=($(compgen -W "$top_commands" -- "$cur"))
      ;;
  esac
}

complete -F _sshm_completions sshm
`;
}

function fishScript(): string {
  return `\
# sshm fish completions
# Generated by: sshm completion --shell fish

function __sshm_hosts
  sshm --completions connect 2>/dev/null
end

function __sshm_groups
  sshm --completions group 2>/dev/null
end

function __sshm_no_subcommand
  not __fish_seen_subcommand_from init sync host group connect c completion
end

# Top-level commands
complete -c sshm -f -n '__sshm_no_subcommand' -a 'init'       -d 'Initialise sshm'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'sync'       -d 'Force regenerate SSH config'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'host'       -d 'Manage SSH hosts'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'group'      -d 'Manage host groups'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'connect'    -d 'Connect to a host'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'c'          -d 'Connect to a host'
complete -c sshm -f -n '__sshm_no_subcommand' -a 'completion' -d 'Generate shell completion script'

# connect / c — dynamic host completions
complete -c sshm -f -n '__fish_seen_subcommand_from connect c' -a '(__sshm_hosts)'

# host subcommands
complete -c sshm -f -n '__fish_seen_subcommand_from host; and not __fish_seen_subcommand_from add edit remove list move' -a 'add'    -d 'Add a host'
complete -c sshm -f -n '__fish_seen_subcommand_from host; and not __fish_seen_subcommand_from add edit remove list move' -a 'edit'   -d 'Edit a host'
complete -c sshm -f -n '__fish_seen_subcommand_from host; and not __fish_seen_subcommand_from add edit remove list move' -a 'remove' -d 'Remove a host'
complete -c sshm -f -n '__fish_seen_subcommand_from host; and not __fish_seen_subcommand_from add edit remove list move' -a 'list'   -d 'List all hosts'
complete -c sshm -f -n '__fish_seen_subcommand_from host; and not __fish_seen_subcommand_from add edit remove list move' -a 'move'   -d 'Move host to group'

# host edit/remove/move — dynamic host completions
complete -c sshm -f -n '__fish_seen_subcommand_from host; and __fish_seen_subcommand_from edit remove move' -a '(__sshm_hosts)'

# group subcommands
complete -c sshm -f -n '__fish_seen_subcommand_from group; and not __fish_seen_subcommand_from add edit remove list' -a 'add'    -d 'Create a group'
complete -c sshm -f -n '__fish_seen_subcommand_from group; and not __fish_seen_subcommand_from add edit remove list' -a 'edit'   -d 'Edit a group'
complete -c sshm -f -n '__fish_seen_subcommand_from group; and not __fish_seen_subcommand_from add edit remove list' -a 'remove' -d 'Remove a group'
complete -c sshm -f -n '__fish_seen_subcommand_from group; and not __fish_seen_subcommand_from add edit remove list' -a 'list'   -d 'List all groups'

# group edit/remove — dynamic group completions
complete -c sshm -f -n '__fish_seen_subcommand_from group; and __fish_seen_subcommand_from edit remove' -a '(__sshm_groups)'
`;
}

// ---------------------------------------------------------------------------
// Install paths per shell
// ---------------------------------------------------------------------------

function resolveInstallPath(shell: string): { path: string; hint: string } {
  const home = homedir();
  if (shell === "zsh") {
    // Prefer ~/.zsh/completions if it exists or if it's in the user's fpath
    // (common custom setup). Fall back to ~/.config/zsh/completions.
    const preferred = join(home, ".zsh", "completions");
    const xdg = join(home, ".config", "zsh", "completions");
    const dir = existsSync(preferred) ? preferred : xdg;
    return {
      path: join(dir, "_sshm"),
      hint: `Add to .zshrc if not already present:\n  fpath+=(${dir})\n  autoload -Uz compinit; compinit`,
    };
  }
  if (shell === "bash") {
    const dir = join(home, ".local", "share", "bash-completion", "completions");
    return { path: join(dir, "sshm"), hint: "" };
  }
  if (shell === "fish") {
    const dir = join(home, ".config", "fish", "completions");
    return { path: join(dir, "sshm.fish"), hint: "" };
  }
  throw new Error(`Unknown shell: ${shell}`);
}

function scriptForShell(shell: string): string {
  if (shell === "zsh") return zshScript();
  if (shell === "bash") return bashScript();
  if (shell === "fish") return fishScript();
  throw new Error(`Unknown shell: ${shell}`);
}

// ---------------------------------------------------------------------------
// Register
// ---------------------------------------------------------------------------

export function registerCompletionCommand(program: Command): void {
  const completion = program
    .command("completion")
    .description("Manage shell completion scripts");

  // Print to stdout
  completion
    .command("print")
    .description("Print the completion script to stdout (for piping)")
    .requiredOption("--shell <shell>", "Shell type: zsh, bash, or fish")
    .action((opts) => {
      const shell = opts.shell as string;
      if (!["zsh", "bash", "fish"].includes(shell)) {
        clack.log.error(`Unknown shell: ${chalk.bold(shell)}. Use zsh, bash, or fish.`);
        process.exit(1);
      }
      process.stdout.write(scriptForShell(shell));
    });

  // Install directly to the right location
  completion
    .command("install")
    .description("Install the completion script to the correct location for your shell")
    .option("--shell <shell>", "Shell type: zsh, bash, or fish (default: auto-detect from $SHELL)")
    .action(async (opts) => {
      clack.intro(chalk.cyan("sshm completion install"));

      const rawShell = (opts.shell as string | undefined) ?? process.env["SHELL"] ?? "";
      const shell = rawShell.includes("zsh")
        ? "zsh"
        : rawShell.includes("fish")
          ? "fish"
          : rawShell.includes("bash")
            ? "bash"
            : undefined;

      if (!shell) {
        clack.log.error(
          `Could not detect shell from ${chalk.dim(rawShell)}. Pass ${chalk.bold("--shell zsh|bash|fish")} explicitly.`,
        );
        process.exit(1);
      }

      const { path, hint } = resolveInstallPath(shell);

      clack.log.info(`Shell: ${chalk.bold(shell)}`);
      clack.log.info(`Target: ${chalk.dim(path)}`);

      const confirm = await clack.confirm({
        message: `Write completion file to ${chalk.bold(path)}?`,
        initialValue: true,
      });
      if (clack.isCancel(confirm) || !confirm) { clack.outro("Cancelled."); return; }

      mkdirSync(join(path, ".."), { recursive: true });
      writeFileSync(path, scriptForShell(shell), "utf-8");

      clack.log.success(`Completion file written to ${chalk.dim(path)}`);

      if (hint) clack.log.warn(hint);

      clack.outro(
        `${chalk.green("✓")} Open a new terminal (or run ${chalk.bold(`source ~/.${shell}rc`)}) to activate completions`,
      );
    });
}
